### ISSUE TITLE
Great idea but ...

### ISSUE THREAD

**Issue by colindaven** [ebi-gene-expression-group/r-seurat-scripts#15]
Hi,

this is a really nice idea for high throughput data preparation.

As far as I have tested and can see, it has not been updated for the big changes in both Cellranger and Seurat in mid 2019. Are you planning to update this ?

Specifically,  I am trying this 
seurat_test$ ls 68F3/
barcodes.tsv  features.tsv  matrix.mtx

and getting this error:

seurat_test$ seurat-read-10x.R -d 68F3/ -o 68F3
Error in Read10X(data.dir = opt$data_dir) : Gene name file missing
Execution halted

Thanks and best wishes,
Colin

**Comment by pcm32** [comment]
Hi Colin,

We have been working on providing interoperability between these components and the equivalent ones from scanpy and sc3/scater (so that you could mix and match). That has drained resources and we haven't been able to come back to this and update Seurat. Unfortunately now we are not in a position, given that the funding for this project is partly coming to an end, to pursue this. We probably have the man power to review pull requests with these changes, if you have the resources to do such an update. We will keep your request in mind should we find some resources to do it.

Thanks,
Pablo

**Comment by colindaven** [comment]
Hi Pablo,

thanks for the answer. Unfortunately we're a core unit so have little time for mid to large projects like this. We'll have to start establishing Seurat pipelines internally to better assist those customers which aren't familiar with R.

Best wishes,
Colin

**Comment by pcm32** [comment]
Hi @colindaven we have started a migration to seurat 3 #16. Contributions welcomed!

**Comment by colindaven** [comment]
Thanks for the update. We are testing this. Sorry for the lack of contributions, we are just starting out with seurat really here.

**Comment by pcm32** [comment]
I will close this since as you might noticed it we released the update. Don't worry, as long as you can cite later on a paper that we are working on where we describe all of these (scanpy-scripts, seurat-scripts, etc and our Galaxy/Nextflow setups), all good! Of course contributions and bug reports always welcomed!
